# Generated by Django 3.2.4 on 2023-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=50)),
                ('emisor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('codigoSMTP', models.CharField(max_length=50)),
                ('contenido', models.TextField(max_length=200)),
            ],
        ),
    ]
